name: Build Steam Runtime

on:
  push: {}
  pull_request: {}

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        branch:
          - scout
          - heavy
          - sniper
          - soldier
        arch:
          - x86_64
        include:
          - branch: scout
            arch: 'i386'
          - branch: heavy
            arch: 'i386'

    runs-on: ubuntu-latest
    container: docker.io/freedesktopsdk/flatpak:22.08-x86_64

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build runtime
        run: |
          make runtime BRANCH=${{ matrix.branch }} ARCH=${{ matrix.arch }}
